Add apply command

diff --git a/internal-ca b/internal-ca
--- a/internal-ca
+++ b/internal-ca
@@ -31,6 +31,10 @@ DESCRIPTION
             Move pem files and ca-certs.yaml in the gopass store
             Then add and commit others files generated ()
 
+      apply
+
+            Create generated CA and cert-manager issuer in the K8S cluster
+
       -s, --store STORE_NAME
 
             Name of the gopass store used to store certifcate. (Default: caascad)
@@ -138,6 +142,11 @@ publish() {
   git -C "$GITSTORE" push
 }
 
+apply() {
+  gopass caascad/internal-ca/test/ca-certs.yaml.b64 | base64 -d | kubectl apply -f -
+  _tmpl_ca-issuer_yaml | kubectl apply -f -
+}
+
 _continue() {
   [ $BATCH -eq 1 ] && return 0
   read -p "Do you want to continue? [y/N]" -n 1 -r
@@ -185,12 +194,12 @@ renew() {
 }
 
 _git_check() {
-  echo "== Check git repo is updated $GITSTORE =="
+  echo "== Check local keystore state =="
   # https://stackoverflow.com/a/3278427
 
-  if ! git -C "$GITSTORE" remote update origin
+  if ! git -C "$GITSTORE" remote update origin 2>/dev/null
   then
-    echo "== Fail to update =="
+    echo "Fail to update keystore"
     exit 3
   fi
 
@@ -291,7 +300,7 @@ _parsing() {
   COMMAND="$1"
 
   case ${COMMAND} in
-    generate | renew | publish | help )
+    generate | renew | publish | apply | help )
       ;;
     * )
       echo "== Unkown command $COMMAND =="
@@ -364,7 +373,7 @@ fi
 
 _git_check
 
-echo "== Force gopass sync =="
+echo "== Syncing =="
 gopass sync -s "$STORE_NAME"
 
 if [ $BATCH -eq 1 ]; then
